version: '3.8'

services:
  vex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - vex-network
  mongodb:
    image: mongo:latest
    container_name: vex-mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: vex
        MONGO_INITDB_ROOT_PASSWORD: password
    ports:
        - "27017:27017"
    volumes:
        - mongodb_data:/data/db
    networks:
        - vex-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: vex-mongo-express
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: vex
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
        - "8081:8081"
    networks:
        - vex-network
    depends_on:
        - mongodb
    restart: unless-stopped

networks:
  vex-network:
    driver: bridge

volumes:
  mongodb_data:
      name: vex-mongodb-data