mqtt:
    host: "localhost"
    port: 1883
    clientId: "tx-processor"
    topic: "ckb.transactions.proposed.detailed"
    reconnectPeriod: 1000
    qos: 1

filters:
    - name: "generic" # this is for every transaction
      filter: "anyway"
      processor: "anyway"
    - name: "dao"
      filter: "codeHash"
      codeHash: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
      processor: "dao"

mongodb:
    uri: "mongodb://vex:password@localhost:27017/vex?authSource=admin"
    options:
        socketTimeoutMS: 30000
        connectTimeoutMS: 30000
        serverSelectionTimeoutMS: 5000

retry:
    maxAttempts: 3
    initialDelay: 1000
    maxDelay: 5000
